import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { SiteHeader } from "@/components/SiteHeader";
import { SiteFooter } from "@/components/SiteFooter";
import { PageHero } from "@/components/PageHero";
import { email, isLocale, locales, whatsapp, whatsappUrl, type Locale } from "@/lib/site";

const copy = {
  en: { title: "Become Our Partner", lead: "We are looking for partners in Russia for industrial water treatment solutions.", who: "Who we work with", groups: ["Russian distributors", "Water treatment companies", "Engineering companies", "Boiler equipment suppliers"], value: "Partnership focus", cards: [["Industrial product range", "FR-series scale prevention systems from DN25 to DN350, with application-specific customization available."], ["Technical coordination", "Project discussion based on actual pipe diameter, flow, pressure and operating conditions."], ["Long-term market development", "Cooperation focused on industrial customers, engineering projects and local channel development."]], cta: "Discuss partnership", note: "Please include your company profile, market coverage and target industries." },
  ru: { title: "Станьте нашим партнёром", lead: "Мы ищем партнёров в России для продвижения решений промышленной водоподготовки.", who: "С кем мы сотрудничаем", groups: ["Российские дистрибьюторы", "Компании водоподготовки", "Инжиниринговые компании", "Поставщики котельного оборудования"], value: "Направления партнёрства", cards: [["Промышленная линейка", "Системы защиты от накипи серии FR от DN25 до DN350; возможна адаптация под проект."], ["Техническая координация", "Обсуждение проекта по фактическому диаметру трубы, расходу, давлению и условиям эксплуатации."], ["Долгосрочное развитие рынка", "Совместная работа с промышленными заказчиками, инженерными проектами и местными каналами продаж."]], cta: "Обсудить партнёрство", note: "Укажите профиль вашей компании, территорию работы и целевые отрасли." },
  zh: { title: "成为我们的合作伙伴", lead: "我们正在俄罗斯寻找工业水处理解决方案合作伙伴。", who: "合作对象", groups: ["俄罗斯经销商", "水处理公司", "工程公司", "锅炉设备供应商"], value: "合作重点", cards: [["工业产品系列", "FR系列水垢处理设备覆盖DN25至DN350，并可按实际应用定制。"], ["技术协同", "根据实际管径、流量、压力和运行条件讨论项目方案。"], ["长期市场开发", "面向工业客户、工程项目和本地渠道开展长期合作。"]], cta: "洽谈合作", note: "来信请附公司简介、市场覆盖区域和目标行业。" },
} satisfies Record<Locale, object>;
export function generateStaticParams(){return locales.map(locale=>({locale}));}
export async function generateMetadata({params}:{params:Promise<{locale:string}>}):Promise<Metadata>{const {locale}=await params;const l:Locale=isLocale(locale)?locale:"ru";return{title:`${copy[l].title} | 辽宁联盛`,description:copy[l].lead,alternates:{canonical:`/${l}/partner`}};}
export default async function Partner({params}:{params:Promise<{locale:string}>}){const{locale}=await params;if(!isLocale(locale))notFound();const t=copy[locale];return <main className="site-shell"><SiteHeader locale={locale} active="partner"/><PageHero eyebrow="Russia market cooperation" title={t.title} lead={t.lead}><div className="buttons"><a className="button primary" href={`mailto:${email}`}>{t.cta}</a><a className="button" href={whatsappUrl} target="_blank" rel="noreferrer">WhatsApp</a></div></PageHero><section className="section"><div className="container split"><div><div className="section-label">{t.who}</div><h2 className="section-title">Industrial channels and engineering partners.</h2></div><div className="partner-types">{t.groups.map((g:string)=><div key={g}>{g}</div>)}</div></div></section><section className="section pale"><div className="container"><div className="section-label">{t.value}</div><div className="partner-card-grid">{t.cards.map(([h,p]:string[],i:number)=><article className="partner-card" key={h}><b>0{i+1}</b><h2>{h}</h2><p>{p}</p></article>)}</div></div></section><section className="contact-strip"><div className="container"><div><span className="eyebrow">Partner enquiry</span><h2>{t.cta}</h2><p>{t.note}</p></div><div className="contact-links"><a href={`mailto:${email}`}>{email}</a><a href={whatsappUrl} target="_blank" rel="noreferrer">WhatsApp: {whatsapp}</a></div></div></section><SiteFooter locale={locale}/></main>}
