import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { SiteHeader } from "@/components/SiteHeader";
import { SiteFooter } from "@/components/SiteFooter";
import { PageHero } from "@/components/PageHero";
import { email, isLocale, locales, siteUrl, specifications, type Locale } from "@/lib/site";

const copy = {
  en: { eyebrow: "Industrial water treatment equipment", title: "Multi-frequency Crystal Core Scale Prevention System", lead: "A physical water treatment device for industrial circulating water, boilers, pipelines and heat-exchange systems.", sections: ["Product Introduction", "Working Principle", "Technical Advantages", "Installation Method", "Application Conditions", "Technical Documents"], intro: "The in-line system is designed to reduce scale formation without chemical agents. The supplied materials describe water passing through a crystal core, impeller and multi-frequency disturbance field.", principle: "Preset natural-frequency information is written into the crystal core. Micro-vibrations act on water and scale-forming mineral molecules as water passes through the device, reducing deposition; existing scale is described as gradually loosening into a sand-like state.", advantages: [["Physical water treatment", "An in-line physical treatment approach."], ["Chemical-free", "No chemical agents are added to the water."], ["Environmentally friendly", "No chemical dosing is required by the treatment process."], ["Reduce scale formation", "Designed to reduce the deposition of scale-forming minerals."], ["Reduce maintenance cost", "Low-maintenance operation can reduce routine treatment work."]], install: ["Select the model to match the pipe diameter at the installation point.", "Install at the protected equipment inlet or after the shut-off valve at the pump outlet.", "Align the arrow on the device body with the direction of water flow.", "For circulating water, install on both return and make-up lines; treat make-up water before it enters the circuit.", "Treat ambient-temperature water before heating. Special water requires customized selection."], conditions: [["Standard range", "DN25-DN350"], ["Water temperature", "5-85°C"], ["Flow velocity", "0.5-2.0 m/s"], ["Pressure options", "1.0 / 1.6 / 2.5 MPa"]], docs: "Download product catalogue, technical manual and installation guide.", request: "Request technical support", headers: ["Model", "Pipe DN (mm)", "Max. D (mm)", "Height H (mm)", "Flow (m³/h)", "Connection", "Pressure (MPa)"], note: "Dimensions shown are for GB-standard 1.0 MPa flanges. Dimensions are adjusted for 1.6 MPa or 2.5 MPa flanges. Other sizes may be customized." },
  ru: { eyebrow: "Оборудование для промышленной водоподготовки", title: "Многочастотная система защиты от накипи с кристаллическим сердечником", lead: "Устройство физической обработки воды для промышленных циркуляционных систем, котлов, трубопроводов и теплообменников.", sections: ["Описание продукта", "Принцип работы", "Технические преимущества", "Способ монтажа", "Условия применения", "Технические документы"], intro: "Встраиваемая система предназначена для снижения образования накипи без химических реагентов. В материалах описано прохождение воды через кристаллический сердечник, крыльчатку и многочастотное возмущающее поле.", principle: "Информация о заданных собственных частотах записана в кристаллическом сердечнике. При прохождении воды микроколебания воздействуют на воду и накипеобразующие минералы, уменьшая отложения; существующая накипь постепенно разрыхляется до пескообразного состояния.", advantages: [["Физическая обработка воды", "Встраиваемый физический метод обработки."], ["Без химических реагентов", "В воду не добавляются химические реагенты."], ["Экологичный подход", "Процесс не требует химического дозирования."], ["Снижение образования накипи", "Система предназначена для уменьшения отложения минералов."], ["Снижение затрат на обслуживание", "Низкие требования к обслуживанию сокращают объём регулярных работ."]], install: ["Подберите модель по диаметру трубы в точке монтажа.", "Установите устройство перед защищаемым оборудованием или после запорного клапана на выходе насоса.", "Совместите стрелку на корпусе с направлением потока воды.", "В циркуляционной системе устанавливайте на обратной и подпиточной линиях; обрабатывайте подпиточную воду до ввода в контур.", "Обрабатывайте воду нормальной температуры до нагрева. Для особой воды требуется индивидуальный подбор."], conditions: [["Стандартный диапазон", "DN25-DN350"], ["Температура воды", "5-85°C"], ["Скорость потока", "0,5-2,0 м/с"], ["Рабочее давление", "1,0 / 1,6 / 2,5 МПа"]], docs: "Скачайте каталог, техническое руководство и инструкцию по монтажу.", request: "Запросить техническую поддержку", headers: ["Модель", "DN трубы (мм)", "Макс. D (мм)", "Высота H (мм)", "Расход (м³/ч)", "Соединение", "Давление (МПа)"], note: "Размеры указаны для фланцев GB на 1,0 МПа. Для фланцев 1,6 или 2,5 МПа размеры корректируются. Другие размеры изготавливаются по запросу." },
  zh: { eyebrow: "工业水处理设备", title: "多频级晶芯水垢处理器", lead: "用于工业循环水、锅炉、管道及换热系统的物理水处理设备。", sections: ["产品介绍", "工作原理", "技术优势", "安装方法", "应用条件", "技术资料"], intro: "该在线式系统用于在不添加化学药剂的情况下减少水垢形成。资料描述水流依次通过晶芯、叶轮和多频扰动场。", principle: "预设的自然频率信息被写入晶芯。水流经过设备时，微振动作用于水和成垢矿物分子，减少沉积；原有水垢会逐渐松散并呈沙状。", advantages: [["物理水处理", "采用管道在线式物理处理方式。"], ["无需化学药剂", "不向水中添加化学药剂。"], ["环境友好", "处理过程无需化学加药。"], ["减少水垢形成", "用于减少成垢矿物沉积。"], ["降低维护成本", "低维护运行可减少日常处理工作。"]], install: ["根据安装位置的管径选择对应型号。", "安装在被保护设备入口处，或水泵出口截止阀之后。", "设备壳体箭头应与介质流向一致。", "循环水系统应在回水管和补水管安装，补水进入系统前先进行处理。", "常温水宜在加热前处理；特殊水质需要定制选型。"], conditions: [["标准范围", "DN25-DN350"], ["水温", "5-85°C"], ["流速", "0.5-2.0 m/s"], ["压力选项", "1.0 / 1.6 / 2.5 MPa"]], docs: "下载产品目录、技术手册和安装指南。", request: "咨询技术支持", headers: ["型号", "管径 DN (mm)", "最大直径 D (mm)", "高度 H (mm)", "流量 (m³/h)", "连接方式", "压力 (MPa)"], note: "表中尺寸为1.0 MPa国标法兰尺寸，选择1.6 MPa或2.5 MPa法兰时尺寸相应调整，其他规格可按应用定制。" },
} satisfies Record<Locale, object>;

export function generateStaticParams() { return locales.map(locale => ({ locale })); }
export async function generateMetadata({ params }: { params: Promise<{ locale: string }> }): Promise<Metadata> { const { locale } = await params; const l: Locale = isLocale(locale) ? locale : "en"; const t = copy[l]; return { title: `${t.title} | 辽宁联盛`, description: t.lead, alternates: { canonical: `/${l}/product`, languages: { en: "/en/product", ru: "/ru/product", "zh-CN": "/zh/product" } }, openGraph: { title: t.title, description: t.lead, images: ["/og.webp"] } }; }

export default async function Product({ params }: { params: Promise<{ locale: string }> }) {
  const { locale } = await params; if (!isLocale(locale)) notFound(); const t = copy[locale];
  const schema = { "@context": "https://schema.org", "@type": "Product", name: t.title, manufacturer: { "@type": "Organization", name: "辽宁联盛" }, category: "Industrial water treatment equipment", url: `${siteUrl}/${locale}/product`, description: t.lead };
  return <main className="site-shell"><SiteHeader locale={locale} active="product" /><PageHero eyebrow={t.eyebrow} title={t.title} lead={t.lead}><div className="buttons"><a href={`mailto:${email}`} className="button primary">{t.request}</a><Link href={`/${locale}/documents`} className="button">{t.sections[5]}</Link></div></PageHero>
    <section className="spec-band"><div className="container spec-band-grid">{t.conditions.map(([a,b]: string[]) => <div className="spec-band-item" key={a}><strong>{b}</strong><span>{a}</span></div>)}</div></section>
    <section className="section"><div className="container split"><div><div className="section-label">01 · {t.sections[0]}</div><h2 className="section-title">{t.title}</h2></div><p className="body-copy">{t.intro}</p></div></section>
    <section className="section pale"><div className="container split"><div><div className="section-label">02 · {t.sections[1]}</div><h2 className="section-title">Crystal core · Impeller · Multi-frequency field</h2></div><p className="body-copy">{t.principle}</p></div></section>
    <section className="section dark-section"><div className="container"><div className="section-label">03 · {t.sections[2]}</div><div className="benefit-grid five">{t.advantages.map(([h,p]: string[], i: number) => <article className="benefit" key={h}><strong>0{i+1}</strong><h3>{h}</h3><p>{p}</p></article>)}</div></div></section>
    <section className="section"><div className="container install-grid"><div><div className="section-label">04 · {t.sections[3]}</div><h2 className="section-title">{t.sections[4]}</h2><div className="condition-list">{t.conditions.map(([a,b]: string[]) => <div key={a}><span>{a}</span><strong>{b}</strong></div>)}</div></div><div className="install-list">{t.install.map((item: string) => <div className="install-item" key={item}>{item}</div>)}</div></div></section>
    <section className="section pale"><div className="container"><div className="section-label">FR Series</div><h2 className="section-title">DN25-DN350</h2><div className="table-wrap"><table className="spec-table"><thead><tr>{t.headers.map((h: string) => <th key={h}>{h}</th>)}</tr></thead><tbody>{specifications.map(row => <tr key={row[0]}>{row.map((v,i) => <td key={i}>{v}</td>)}</tr>)}</tbody></table></div><p className="table-note">{t.note}</p></div></section>
    <section className="product-cta"><div className="container product-cta-grid"><div><span className="eyebrow">06 · {t.sections[5]}</span><h2>{t.docs}</h2></div><Link href={`/${locale}/documents`} className="button primary">{t.sections[5]}</Link></div></section>
    <SiteFooter locale={locale} /><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }} />
  </main>;
}
